installedApps:
  - git
sfdxPluginsStdout: "@salesforce/sfdx-scanner \e[2m3.10.0\e[22m\nbbdoc \e[2m4.1.0\e[22m\nsfdmu \e[2m4.26.10\e[22m\nsfdx-essentials \e[2m2.12.0\e[22m\nsfdx-git-delta \e[2m5.13.3\e[22m\nsfdx-hardis \e[2m3.12.3\e[22m\ntexei-sfdx-plugin \e[2m1.17.2\e[22m\n"
