public with sharing class DreamforceClass {
    
    public static String sayHello(){
        return 'Hello dreamforce 22!';
    }

    public static String bye(){
        return 'bye';
    }

    public static void check(){
        //second change
    }

    public static void newMethod(){
        //added from dx repo!
    }

    public static Boolean customerEngineers(){
        return true;
    }
}